pinentry-program ~/.local/sbin/pinentry-auto

enable-ssh-support

# Important pour Wayland
# Assure le focus clavier
grab
# Évite des bugs de cache
no-allow-external-cache

# Durée de cache (secondes)
# 10 minutes
default-cache-ttl 600
# 2 heures
max-cache-ttl 7200

# Cache SSH
default-cache-ttl-ssh 3600
max-cache-ttl-ssh 7200
