#!/usr/bin/env bash

DNS_IP="1.1.1.1"
DOCKER_API_VERSION="1.41"

DATA_DIR="${HOME}/Data/adguardhome"
CONFIG_FILE_PATH="${HOME}/.config/local/net.json"

CONTAINER_NAME="local-net"


if ! command -v jq &>/dev/null; then
  echo "Error: jq is not installed."
  exit 1
fi

# Start local-net
if [ ! -f "$CONFIG_FILE_PATH" ]; then
  echo "Error: config file does not exist."
  exit 1
fi

mkdir -p "$DATA_DIR"/{work,conf}

if [ "$(docker container ls --filter "name=${CONTAINER_NAME}" --quiet | wc -l)" -eq 0 ]; then
  echo -e "Running container ${CONTAINER_NAME}"

  if [ "$(grep -c "ID=nixos" /etc/os-release)" -eq 0 ]; then
    # Configure resolv.conf
    LOCAL_IP_DNS="$(jq -r '.ip_addresses.dns.ip_address' "$CONFIG_FILE_PATH")"

    if ! grep "$LOCAL_IP_DNS" /etc/systemd/resolved.conf > /dev/null ; then
      sudo sed -i -e 's/#DNSStubListener=yes/DNSStubListener=no/' -e "s/#DNS=/DNS=${LOCAL_IP_DNS}/" /etc/systemd/resolved.conf

      sudo systemctl restart systemd-resolved
    fi
  fi

  exec docker container run \
    -t \
    --rm \
    --mount type=bind,src=/var/run/dbus,dst=/var/run/dbus \
    --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
    --mount type=bind,src=${CONFIG_FILE_PATH},dst=/tmp/local-net.json \
    --mount type=bind,src=${DATA_DIR}/work,dst=/opt/adguardhome/work \
    --mount type=bind,src=${DATA_DIR}/conf,dst=/opt/adguardhome/conf \
    --net host \
    --dns "$DNS_IP" \
    --security-opt seccomp=unconfined \
    --security-opt apparmor=unconfined \
    --cap-add=NET_ADMIN \
    --env DOCKER_API_VERSION=$DOCKER_API_VERSION \
    --name "$CONTAINER_NAME" \
    juli3nk/local-net \
      -debug
fi
