#!/usr/bin/env bash

. "${HOME}/.local/lib/utils.sh"

POLKIT_BIN_NAME="polkit-mate-authentication-agent-1"
POLKIT_BIN_PATH="/usr/lib/x86_64-linux-gnu/polkit-mate"


for cmd in lsb_release; do
  command_exists "$cmd"
done

if [ $(lsb_release --id --short | sed 's/"//g') == "NixOS" ]; then
  # find /nix/store/ -name 'polkit-mate-authentication-agent-1'
  POLKIT_BIN_PATH="$(nix path-info nixpkgs#mate.mate-polkit)/libexec"
fi

POLKIT_BIN_FULLPATH="${POLKIT_BIN_PATH}/${POLKIT_BIN_NAME}"

exec "$POLKIT_BIN_FULLPATH"
