import = ["~/.config/alacritty/catppuccin-mocha.toml"]
live_config_reload = true

[bell]
command = "None"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 9

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
decorations = "full"
dynamic_title = true
option_as_alt = "Both"
startup_mode = "Maximized"

[window.dimensions]
columns = 160
lines = 80

[window.padding]
x = 4
y = 4
